### ISSUE TITLE
Language Support for Typescript/Angular2 Decorator 

### ISSUE THREAD

**Issue by ghost** [Jaredk3nt/laserwave#1]
Hi, 

a language support for Typescript would be amazing.

Thanks in advantage

**Comment by Jaredk3nt** [comment]
@ghost if you have a good example file that has all or most of angular/typescript features that need syntax highlighting that would make development much easier. Sorry I don't write any Angular so I don't have any examples to test with.

But I will work on it!

**Comment by lcatania** [comment]
@Jaredk3nt Here is an example file with all "features" i could think of.

[https://pastebin.com/raw/ZhsTWk6R](url)

![color_scheme](https://user-images.githubusercontent.com/41628606/43147019-5dc8c434-8f62-11e8-92d4-9d4241a881a0.png)

**Comment by Jaredk3nt** [comment]
Pushed a new version up of LaserWave adding .ts support. 

Closing the issue for now, but if I missed anything feel free to comment on this issue with the specifics and I will try to add a fix as quickly as I can.
