### ISSUE TITLE
HyperTerminal Port

### ISSUE THREAD

**Issue by oscarmcm** [Jaredk3nt/laserwave#10]
Hey mate, i just made a theme port to [Hyper Terminal](http://hyper.is/), [check this](https://github.com/oscarmcm/hyperwave) and thanks 😄 

<img width="634" alt="imagen" src="https://user-images.githubusercontent.com/2553459/43660893-8a03682a-971d-11e8-97e8-302c0ffbb469.png">

**Comment by Jaredk3nt** [comment]
Thanks for the credit man, glad you enjoy the theme!

**Comment by Jaredk3nt** [comment]
@oscarmcm Heres a pic of the theme I have been using on iterm2 to match it, using the pink as red
<img width="654" alt="image" src="https://user-images.githubusercontent.com/6362515/43690465-28f0999a-98d0-11e8-8dd7-db28bd6fff9d.png">

**Comment by oscarmcm** [comment]
thanks mate 🤙 released a new version
