### ISSUE TITLE
Firefox Color theme

### ISSUE THREAD

**Issue by makmm** [Jaredk3nt/laserwave#11]
I have made a Firefox Color theme. It doesn't look that good but I'm making my rice around your color scheme and it's a lot better like this.

Here's the theme: https://color.firefox.com/?theme=XQAAAALtAAAAAAAAAABBKYhm849SCiazH1KEGccwS-xNVAVNKZgvGNrt6AXjaGrFzneWKoz-M0DYqqhpY1Z8_d631Fj78lY43WZGklOR-P5097wV4rZg79b6sjiES6iSv9GVOp8rVou_J7HIcySg3IZyP2uiQBLKLrPsVnUEmkbebQDWFuLTAbLeI--pP_tAVzfBR85EVgjj4dprToUwH_zhjwA

**Comment by Jaredk3nt** [comment]
I would love to see a full picture of your setup!
