### ISSUE TITLE
Comments very difficult to read

### ISSUE THREAD

**Issue by cameronstinson4** [Jaredk3nt/laserwave#12]
Was hoping it would be possible to change the color that comments are because it's very difficult to read with screen brightness lower than max.  The problem seems to be persist across both my Pixelbook and MBP. 

Thanks!

Attached are pictures of an example, and a correction with a lighter color that I can PR if you think this could be changed.

![before](https://user-images.githubusercontent.com/22205546/47119173-da29b200-d237-11e8-86e4-bf0497564eee.png)
![screenshot_2018-10-17_17-56-46](https://user-images.githubusercontent.com/22205546/47119179-e31a8380-d237-11e8-9380-173e0de7d54d.png)

(color #a494b5 for example)

**Comment by Jaredk3nt** [comment]
I'm certainly not opposed to that I could see how it can be hard to read (i'm a bright screen person so I haven't really noticed it). That's a bit pink IMO, how about something like: #91889b

<img width="647" alt="image" src="https://user-images.githubusercontent.com/6362515/47129092-8760f200-d259-11e8-9773-280e1a77313a.png">
