### ISSUE TITLE
Untracked file color

### ISSUE THREAD

**Issue by cassiobock** [Jaredk3nt/laserwave#14]
Could you use another color to represent untracked files? It does look the same as the ignored files in Git.

Using laserwave:
![image](https://user-images.githubusercontent.com/3936166/49151415-fb7dc380-f2f6-11e8-8408-a6a6b2a91096.png)

Using other theme:
![image](https://user-images.githubusercontent.com/3936166/49151441-0b95a300-f2f7-11e8-8558-876340714a0d.png)

**Comment by Jaredk3nt** [comment]
Updated to #40b4c4 in v1.2.3!
