### ISSUE TITLE
Default VSCode colors

### ISSUE THREAD

**Issue by wldyslw** [Jaredk3nt/laserwave#16]
Hi, and first of all, thank you for such a beautiful theme!

Could you please change hover & focus colors in explorer? Seems like they're VSCode's default now, as on screenshot down below:

![image](https://user-images.githubusercontent.com/13451336/54210557-c6d1f880-44f0-11e9-9f73-9f532eb384bb.png)

Also the same issue with default colors is present on title bar when window is not focused (it may be hard to see):

![image](https://user-images.githubusercontent.com/13451336/54211107-c71ec380-44f1-11e9-93ad-825578e8c43b.png)

**Comment by Jaredk3nt** [comment]
I will look into any left over defaults (sorry for the huge delay, I haven't looked at this in awhile)

**Comment by Jaredk3nt** [comment]
I have added changes for list highlighting, input colors, and some other little misc things in v1.2.4! I'm going to go ahead and close this but feel free to open it again if there is anything that you still see.

**Comment by wldyslw** [comment]
Nice, thank you!
