### ISSUE TITLE
Color for Variables

### ISSUE THREAD

**Issue by dpunish3r** [Jaredk3nt/laserwave#17]
Hi! Thanks for your work! This theme would be my favorite number 1 if it weren't for a detail in the color scheme. 

The white for the variables contrasts too much and bothers the eyes. A non-pure white such as a #dddddd or maximum a #eeeeee would be ideal. 

Thanks in advance

**Comment by Jaredk3nt** [comment]
I will look into this

**Comment by Jaredk3nt** [comment]
I would recommend the colorCustomization section for overriding values in a specific theme. Here is a link to visual studio's documentation on how to do this, it is fairly straight forward: https://code.visualstudio.com/api/extension-guides/color-theme#workbench-colors

If there is a larger movement to change this I will look into changing the theme, but as of right now this is the best path to take.

**Comment by dpunish3r** [comment]
> I would recommend the colorCustomization section for overriding values in a specific theme. Here is a link to visual studio's documentation on how to do this, it is fairly straight forward: https://code.visualstudio.com/api/extension-guides/color-theme#workbench-colors

Thank you! I searched if that could be done but I didn't find it.
