### ISSUE TITLE
Diff view inserted text is not legible

### ISSUE THREAD

**Issue by TGiles** [Jaredk3nt/laserwave#20]
The inserted text background is not legible when inserting new code blocks into a file.
![image](https://user-images.githubusercontent.com/6314039/67597776-f1985680-f739-11e9-9037-c5aa59a8fe19.png)

I can whip up a fix for this later today. I think the background just needs to be more transparent, but wanted to open a issue so we could start a discussion

I've been using a transparent maximum blue (#40b4c42d) and it seems to cut through better than pearl aqua
![image](https://user-images.githubusercontent.com/6314039/67598046-94e96b80-f73a-11e9-86a3-88825bed8098.png)

**Comment by Jaredk3nt** [comment]
What flow does this come from so I can take a look at it?

**Comment by TGiles** [comment]
I'm assuming you're asking for steps to reproduce (which I should have included in the first place 😬)
Steps to reproduce:
1. Add a file to git repository
2. Add a block of code to previously added file, which triggers the Modified (M) tag in the source control tab
3. View the file in the diff editor
4. Inserted text is hard to read a majority of the time 
![image](https://user-images.githubusercontent.com/6314039/67794480-18fd6500-fa53-11e9-9d68-ea8f688f2437.png)

Something else I noticed is that this might be a monitor setting issue as well. I moved the hard to read diff view between my monitors and noticed some legibility changes.

Let me know if you need any more info!

**Comment by TGiles** [comment]
@Jaredk3nt I pulled the opacity way down (#74dfc41e), but the color looks off to me, for lack of a better description. Here's that previously mentioned color in action: 
![image](https://user-images.githubusercontent.com/6314039/68442887-68087000-01a0-11ea-8bb0-435604f039d1.png)

All the text is more legible to me but it reminds me of the standard vscode styling, but off color. I personally think the maximum blue cuts through more, however I'll defer to your choice on this.

**Comment by Jaredk3nt** [comment]
Actually I think you are right on this one the blue is cleaner. I would still drop the opacity just a bit but I think we can move forward with essentially what you originally suggested
