### ISSUE TITLE
Java support missing `implements` keyword highlighting

### ISSUE THREAD

**Issue by lpedrosa** [Jaredk3nt/laserwave#29]
Really cool theme! Thanks for making this and adding Java support ❤️ 

I believe the theme might not be considering `implements` as a keyword. 

![image](https://user-images.githubusercontent.com/2365589/76340612-c468d100-62f3-11ea-9152-4d565b6f7c4b.png)

Everything else seems to work just fine.

**Comment by Jaredk3nt** [comment]
Fix in v1.2.9 👍
