### ISSUE TITLE
Language(s) Request

### ISSUE THREAD

**Issue by frankdugan3** [Jaredk3nt/laserwave#3]
Love this theme! It would be amazing if Go and Elm were supported as well.

**Comment by Jaredk3nt** [comment]
Hey @frankdugan3 I don't have much experience in either of those but if you could send me some example files that I could test with I will definitely add support!

**Comment by StefanoPernat** [comment]
I agree with @frankdugan3. 

please add Go support.

Your theme is awesome

**Comment by Jaredk3nt** [comment]
@StefanoPernat I'm just waiting on some example code to be able to make it and I will!

**Comment by frankdugan3** [comment]
Sorry for the delay. Here's an example for [Go](https://github.com/golang/example/blob/master/outyet/main.go) and for [Elm](http://elm-lang.org/examples/form).

**Comment by Jaredk3nt** [comment]
Thanks for the examples I finished it up pretty quick. Live in version 1.2.0!
