### ISSUE TITLE
F# support

### ISSUE THREAD

**Issue by Deide** [Jaredk3nt/laserwave#34]
Let's add some F# support to this nice theme. I've had a quick go at it, as well as adding an .editorconfig as can be seen in this [comparison](https://github.com/Jaredk3nt/laserwave/compare/master...Deide:fsharp).

**Comment by Jaredk3nt** [comment]
I don't think I want to add an editorconfig to the project, but if you want to open a PR with the F# updates I will gladly check it out

**Comment by Jaredk3nt** [comment]
<img width="1440" alt="image" src="https://user-images.githubusercontent.com/6362515/125012627-5a635780-e01f-11eb-978c-ed4ec128d500.png">

FSharp is now supported as of `v1.3.0` 🎉
Thank you for your epic patience
