### ISSUE TITLE
Text almost unreadable in the explorer view

### ISSUE THREAD

**Issue by AlbertoFabbri93** [Jaredk3nt/laserwave#36]
Issue Type: <b>Bug</b>

Some cache files are presented grayed out in the explorer view but that makes very difficult to read their names.

Extension version: 1.2.11
VS Code version: Code 1.52.1 (ea3859d4ba2f3e577a159bc91e3074c5d85c0523, 2020-12-16T16:34:46.910Z)
OS version: Windows_NT x64 10.0.19042

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-8250U CPU @ 1.60GHz (8 x 1800)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>opengl: enabled_on<br>protected_video_decode: enabled<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|7.84GB (1.17GB free)|
|Process Argv|--crash-reporter-id 7cd19320-ee8a-45d8-b96c-f694d3262d4d|
|Screen Reader|no|
|VM|0%|
</details>

![Screenshot 2020-12-22 000250](https://user-images.githubusercontent.com/51910894/102830246-34f75f00-43e9-11eb-8888-68660ebe387c.jpg)

**Comment by Jaredk3nt** [comment]
Updated in `v.1.3.0`

<img width="261" alt="image" src="https://user-images.githubusercontent.com/6362515/125012223-b5487f00-e01e-11eb-8eec-f9f943599af4.png">

The ignored git files now pass AA on LaserWave and AAA on the new "LaserWave High Contrast" version
