### ISSUE TITLE
Improve contrast of punctuation

### ISSUE THREAD

**Issue by bhagyas** [Jaredk3nt/laserwave#37]
The Roman Silver does not provide enough contrast against the Raisin Black as the background.

**Comment by Jaredk3nt** [comment]
Updated in `v1.3.0`. Small adjustment that is a bit better on visibility but still in line with the theme

<img width="368" alt="image" src="https://user-images.githubusercontent.com/6362515/125011823-073cd500-e01e-11eb-838f-0ad40a464817.png">

Also added a High Contrast version of laserwave that is AAA for all the colors if you need something a bit stronger 👍
