### ISSUE TITLE
Support diff language view

### ISSUE THREAD

**Issue by TGiles** [Jaredk3nt/laserwave#40]
Currently if you view a `.diff` file with Laserwave, there's no highlighting on the added and removed parts of the diff. This makes it harder to tell which lines were added/removed compared to other color themes. Considering other themes have this feature I guess it's just some additional TextMate that needs to be defined.

@Jaredk3nt what colors out of the palette would you want for this? It looks like the `+` and `-` symbols can be customized to be different that the lines of text they're on as well as the "diff header" since I don't know what it's actually called...the part that says `diff --git a/file b/file`

I feel like I can take this on and get a PR up in a day or two

**Comment by Jaredk3nt** [comment]
I don't think I have used `.diff` files before so I'm not exactly sure what the UI looks like in VS Code. I would imagine it would look like the git diff view though which already has some defined colors

![image](https://user-images.githubusercontent.com/6362515/134595956-a342367b-0d2f-4992-a4c4-543d9b90b236.png)

It basically just uses a transparent version of Maximum Blue and Hot Pink in place or red/green. So as long as it follows that pattern i'm up for it 👍 . Having the -/+ be the full version of the color would be pretty sweet looking as well.

If i'm missing anything post some examples here from other themes and I can weigh in

**Comment by TGiles** [comment]
Gotcha, sounds good. I'll post some examples so you're aware. I'll include the diff file I'm using as part of the examples for future reference.

2077 theme 
![image](https://user-images.githubusercontent.com/6314039/134716761-4e06cacd-b863-4666-8bf8-bde33dfdc002.png)

Dark (visual studio) 
![image](https://user-images.githubusercontent.com/6314039/134716861-66ec9cfc-ba31-4f45-a1b2-e81445254946.png)
