### ISSUE TITLE
Theming for editor gutter for modified, added, deleted lines

### ISSUE THREAD

**Issue by TGiles** [Jaredk3nt/laserwave#42]
Currently, the theme uses the default colors when lines are edited, added, or removed.

![image](https://user-images.githubusercontent.com/6314039/134733494-bd0ed487-e831-488d-b358-d9722ac22dd1.png)

These are controlled by the following tokens:

```
"editorGutter.modifiedBackground":
 "editorGutter.addedBackground": 
"editorGutter.deletedBackground": 
```

where modified corresponds to the blue line in the screenshot, added corresponds to green, and deleted corresponds to red.

I'm guessing added needs to be Maximum Blue, deleted needs to be Hot Pink, but I'm not sure what the modified color should be. I tried with Powder Blue, but that looks too close to Maximum Blue in this case. I then tried Mustard, but it just looks weird to me, for lack of a better justification 😂 Maybe African Violet? dunno

I stumbled upon this because I was trying to figure out what `punctuation.definition.changed.diff` was in #41, and found out we could color the gutter. I can also take this on, basically have a patch ready once you decide what the modified background color should be

**Comment by Jaredk3nt** [comment]
I went ahead and added this in so it didn't wait another month before getting added in 😅 Thanks so much for figuring out how to color those! 

![image](https://user-images.githubusercontent.com/6362515/136141086-3c0b9d1a-b79b-4a8d-b514-2951efc98511.png)

**Comment by TGiles** [comment]
looks sick, glad that the theme keeps improving!
