### ISSUE TITLE
Feature Request: Italic version of code keywords

### ISSUE THREAD

**Issue by sambenskin** [Jaredk3nt/laserwave#8]
Love this theme, any chance of a version with italics for code keywords?

**Comment by Jaredk3nt** [comment]
I've been thinking about doing an italics, good to know there's someone out there who wants it. I'll work on it 🤩

**Comment by sambenskin** [comment]
Brilliant :) As I said your theme is stunning, thanks for taking a look.

Here's an example of what I mean: https://marketplace.visualstudio.com/items?itemName=idbartosz.darkpp-italic

The italics on the code keywords allow the use of the different font like on the "const" keyword in JS

**Comment by Jaredk3nt** [comment]
~~ *LaserWave Italic* ~~ is now live!

**Comment by sambenskin** [comment]
Looks really good! thanks

Small thing, the keyword const in js file isn't italicised, any idea why?
