### ISSUE TITLE
Request to support powershell

### ISSUE THREAD

**Issue by Riiskyy** [Jaredk3nt/laserwave#9]
I mainly use VSCode for PowerShell so support for this would be amazing as I love the colour scheme. Example file is included below.

[examplePoSh.zip](https://github.com/Jaredk3nt/laserwave/files/2253443/examplePoSh.zip)

**Comment by jeremytbrun** [comment]
+1!

**Comment by jeremytbrun** [comment]
💯

**Comment by jeremytbrun** [comment]
I agree!

**Comment by Jaredk3nt** [comment]
Hey yall I have seen this! its a busy week for me hopefully I will get around to it this weekend. Sorry for the delay 😬

**Comment by jeremytbrun** [comment]
By chance any progress on this?

**Comment by Jaredk3nt** [comment]
Added in 1.2.1

**Comment by jeremytbrun** [comment]
I've been testing. It's looking great!
